apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdashboard
  labels:
    app: orderdashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdashboard
  template:
    metadata:
      labels:
        app: orderdashboard
    spec:
      containers:
        - name: orderdashboard
          image: username/orderdashboard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5